version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${DS_PORT_EXTERNAL}:${DS_PORT}"
    environment:
      POSTGRES_USER: ${DS_USER}
      POSTGRES_PASSWORD: ${DS_PASSWORD}
      POSTGRES_DB: ${DS_DATABASE}
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    env_file:
      - .env
    networks:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9500:9500
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"


networks:
  postgres:
    driver: bridge

