version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elastic
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - compatible-with=7
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9500:9500"
